In [1]:
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, execute, Aer
from qiskit.compiler import transpile, assemble
from qiskit.tools.jupyter import *
from qiskit.visualization import *
from math import pi, sqrt
import numpy as np
import copy as cp
import scipy as sp
import math

In [2]:
dataset = [['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
['4', '4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
['5', '5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
['6', '5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
['7', '4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
['8', '5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
['9', '4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
['10', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
['11', '5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
['12', '4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
['13', '4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
['15', '5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
['16', '5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
['17', '5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
['18', '5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
['19', '5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
['20', '5.1', '3.8', '1.5', '0.3', 'Iris-setosa'],
['21', '5.4', '3.4', '1.7', '0.2', 'Iris-setosa'],
['22', '5.1', '3.7', '1.5', '0.4', 'Iris-setosa'],
['23', '4.6', '3.6', '1.0', '0.2', 'Iris-setosa'],
['24', '5.1', '3.3', '1.7', '0.5', 'Iris-setosa'],
['25', '4.8', '3.4', '1.9', '0.2', 'Iris-setosa'],
['26', '5.0', '3.0', '1.6', '0.2', 'Iris-setosa'],
['27', '5.0', '3.4', '1.6', '0.4', 'Iris-setosa'],
['28', '5.2', '3.5', '1.5', '0.2', 'Iris-setosa'],
['29', '5.2', '3.4', '1.4', '0.2', 'Iris-setosa'],
['30', '4.7', '3.2', '1.6', '0.2', 'Iris-setosa'],
['31', '4.8', '3.1', '1.6', '0.2', 'Iris-setosa'],
['32', '5.4', '3.4', '1.5', '0.4', 'Iris-setosa'],
['33', '5.2', '4.1', '1.5', '0.1', 'Iris-setosa'],
['34', '5.5', '4.2', '1.4', '0.2', 'Iris-setosa'],
['35', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
['36', '5.0', '3.2', '1.2', '0.2', 'Iris-setosa'],
['37', '5.5', '3.5', '1.3', '0.2', 'Iris-setosa'],
['38', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
['39', '4.4', '3.0', '1.3', '0.2', 'Iris-setosa'],
['40', '5.1', '3.4', '1.5', '0.2', 'Iris-setosa'],
['41', '5.0', '3.5', '1.3', '0.3', 'Iris-setosa'],
['42', '4.5', '2.3', '1.3', '0.3', 'Iris-setosa'],
['43', '4.4', '3.2', '1.3', '0.2', 'Iris-setosa'],
['44', '5.0', '3.5', '1.6', '0.6', 'Iris-setosa'],
['45', '5.1', '3.8', '1.9', '0.4', 'Iris-setosa'],
['46', '4.8', '3.0', '1.4', '0.3', 'Iris-setosa'],
['47', '5.1', '3.8', '1.6', '0.2', 'Iris-setosa'],
['48', '4.6', '3.2', '1.4', '0.2', 'Iris-setosa'],
['49', '5.3', '3.7', '1.5', '0.2', 'Iris-setosa'],
['50', '5.0', '3.3', '1.4', '0.2', 'Iris-setosa'],
['51', '7.0', '3.2', '4.7', '1.4', 'Iris-versicolor'],
['52', '6.4', '3.2', '4.5', '1.5', 'Iris-versicolor'],
['53', '6.9', '3.1', '4.9', '1.5', 'Iris-versicolor'],
['54', '5.5', '2.3', '4.0', '1.3', 'Iris-versicolor'],
['55', '6.5', '2.8', '4.6', '1.5', 'Iris-versicolor'],
['56', '5.7', '2.8', '4.5', '1.3', 'Iris-versicolor'],
['57', '6.3', '3.3', '4.7', '1.6', 'Iris-versicolor'],
['58', '4.9', '2.4', '3.3', '1.0', 'Iris-versicolor'],
['59', '6.6', '2.9', '4.6', '1.3', 'Iris-versicolor'],
['60', '5.2', '2.7', '3.9', '1.4', 'Iris-versicolor'],
['61', '5.0', '2.0', '3.5', '1.0', 'Iris-versicolor'],
['62', '5.9', '3.0', '4.2', '1.5', 'Iris-versicolor'],
['63', '6.0', '2.2', '4.0', '1.0', 'Iris-versicolor'],
['64', '6.1', '2.9', '4.7', '1.4', 'Iris-versicolor'],
['65', '5.6', '2.9', '3.6', '1.3', 'Iris-versicolor'],
['66', '6.7', '3.1', '4.4', '1.4', 'Iris-versicolor'],
['67', '5.6', '3.0', '4.5', '1.5', 'Iris-versicolor'],
['68', '5.8', '2.7', '4.1', '1.0', 'Iris-versicolor'],
['69', '6.2', '2.2', '4.5', '1.5', 'Iris-versicolor'],
['70', '5.6', '2.5', '3.9', '1.1', 'Iris-versicolor'],
['71', '5.9', '3.2', '4.8', '1.8', 'Iris-versicolor'],
['72', '6.1', '2.8', '4.0', '1.3', 'Iris-versicolor'],
['73', '6.3', '2.5', '4.9', '1.5', 'Iris-versicolor'],
['74', '6.1', '2.8', '4.7', '1.2', 'Iris-versicolor'],
['75', '6.4', '2.9', '4.3', '1.3', 'Iris-versicolor'],
['76', '6.6', '3.0', '4.4', '1.4', 'Iris-versicolor'],
['77', '6.8', '2.8', '4.8', '1.4', 'Iris-versicolor'],
['78', '6.7', '3.0', '5.0', '1.7', 'Iris-versicolor'],
['79', '6.0', '2.9', '4.5', '1.5', 'Iris-versicolor'],
['80', '5.7', '2.6', '3.5', '1.0', 'Iris-versicolor'],
['81', '5.5', '2.4', '3.8', '1.1', 'Iris-versicolor'],
['82', '5.5', '2.4', '3.7', '1.0', 'Iris-versicolor'],
['83', '5.8', '2.7', '3.9', '1.2', 'Iris-versicolor'],
['84', '6.0', '2.7', '5.1', '1.6', 'Iris-versicolor'],
['85', '5.4', '3.0', '4.5', '1.5', 'Iris-versicolor'],
['86', '6.0', '3.4', '4.5', '1.6', 'Iris-versicolor'],
['87', '6.7', '3.1', '4.7', '1.5', 'Iris-versicolor'],
['88', '6.3', '2.3', '4.4', '1.3', 'Iris-versicolor'],
['89', '5.6', '3.0', '4.1', '1.3', 'Iris-versicolor'],
['90', '5.5', '2.5', '4.0', '1.3', 'Iris-versicolor'],
['91', '5.5', '2.6', '4.4', '1.2', 'Iris-versicolor'],
['92', '6.1', '3.0', '4.6', '1.4', 'Iris-versicolor'],
['93', '5.8', '2.6', '4.0', '1.2', 'Iris-versicolor'],
['94', '5.0', '2.3', '3.3', '1.0', 'Iris-versicolor'],
['95', '5.6', '2.7', '4.2', '1.3', 'Iris-versicolor'],
['96', '5.7', '3.0', '4.2', '1.2', 'Iris-versicolor'],
['97', '5.7', '2.9', '4.2', '1.3', 'Iris-versicolor'],
['98', '6.2', '2.9', '4.3', '1.3', 'Iris-versicolor'],
['99', '5.1', '2.5', '3.0', '1.1', 'Iris-versicolor'],
['100', '5.7', '2.8', '4.1', '1.3', 'Iris-versicolor'],
['101', '6.3', '3.3', '6.0', '2.5', 'Iris-virginica'],
['102', '5.8', '2.7', '5.1', '1.9', 'Iris-virginica'],
['103', '7.1', '3.0', '5.9', '2.1', 'Iris-virginica'],
['104', '6.3', '2.9', '5.6', '1.8', 'Iris-virginica'],
['105', '6.5', '3.0', '5.8', '2.2', 'Iris-virginica'],
['106', '7.6', '3.0', '6.6', '2.1', 'Iris-virginica'],
['107', '4.9', '2.5', '4.5', '1.7', 'Iris-virginica'],
['108', '7.3', '2.9', '6.3', '1.8', 'Iris-virginica'],
['109', '6.7', '2.5', '5.8', '1.8', 'Iris-virginica'],
['110', '7.2', '3.6', '6.1', '2.5', 'Iris-virginica'],
['111', '6.5', '3.2', '5.1', '2.0', 'Iris-virginica'],
['112', '6.4', '2.7', '5.3', '1.9', 'Iris-virginica'],
['113', '6.8', '3.0', '5.5', '2.1', 'Iris-virginica'],
['114', '5.7', '2.5', '5.0', '2.0', 'Iris-virginica'],
['115', '5.8', '2.8', '5.1', '2.4', 'Iris-virginica'],
['116', '6.4', '3.2', '5.3', '2.3', 'Iris-virginica'],
['117', '6.5', '3.0', '5.5', '1.8', 'Iris-virginica'],
['118', '7.7', '3.8', '6.7', '2.2', 'Iris-virginica'],
['119', '7.7', '2.6', '6.9', '2.3', 'Iris-virginica'],
['120', '6.0', '2.2', '5.0', '1.5', 'Iris-virginica'],
['121', '6.9', '3.2', '5.7', '2.3', 'Iris-virginica'],
['122', '5.6', '2.8', '4.9', '2.0', 'Iris-virginica'],
['123', '7.7', '2.8', '6.7', '2.0', 'Iris-virginica'],
['124', '6.3', '2.7', '4.9', '1.8', 'Iris-virginica'],
['125', '6.7', '3.3', '5.7', '2.1', 'Iris-virginica'],
['126', '7.2', '3.2', '6.0', '1.8', 'Iris-virginica'],
['127', '6.2', '2.8', '4.8', '1.8', 'Iris-virginica'],
['128', '6.1', '3.0', '4.9', '1.8', 'Iris-virginica'],
['129', '6.4', '2.8', '5.6', '2.1', 'Iris-virginica'],
['130', '7.2', '3.0', '5.8', '1.6', 'Iris-virginica'],
['131', '7.4', '2.8', '6.1', '1.9', 'Iris-virginica'],
['132', '7.9', '3.8', '6.4', '2.0', 'Iris-virginica'],
['133', '6.4', '2.8', '5.6', '2.2', 'Iris-virginica'],
['134', '6.3', '2.8', '5.1', '1.5', 'Iris-virginica'],
['135', '6.1', '2.6', '5.6', '1.4', 'Iris-virginica'],
['136', '7.7', '3.0', '6.1', '2.3', 'Iris-virginica'],
['137', '6.3', '3.4', '5.6', '2.4', 'Iris-virginica'],
['138', '6.4', '3.1', '5.5', '1.8', 'Iris-virginica'],
['139', '6.0', '3.0', '4.8', '1.8', 'Iris-virginica'],
['140', '6.9', '3.1', '5.4', '2.1', 'Iris-virginica'],
['141', '6.7', '3.1', '5.6', '2.4', 'Iris-virginica'],
['142', '6.9', '3.1', '5.1', '2.3', 'Iris-virginica'],
['143', '5.8', '2.7', '5.1', '1.9', 'Iris-virginica'],
['144', '6.8', '3.2', '5.9', '2.3', 'Iris-virginica'],
['145', '6.7', '3.3', '5.7', '2.5', 'Iris-virginica'],
['146', '6.7', '3.0', '5.2', '2.3', 'Iris-virginica'],
['147', '6.3', '2.5', '5.0', '1.9', 'Iris-virginica'],
['148', '6.5', '3.0', '5.2', '2.0', 'Iris-virginica'],
['149', '6.2', '3.4', '5.4', '2.3', 'Iris-virginica'],
['150', '5.9', '3.0', '5.1', '1.8', 'Iris-virginica']]

unlabelled_dataset = [np.array([float(data[1]) for data in dataset]), np.array([float(data[2]) for data in dataset]), 
                      np.array([float(data[3]) for data in dataset]), np.array([float(data[4]) for data in dataset])]

means = [sum(unlabelled_dataset[i])/150 for i in range(4)]
stdevs = [(sum(unlabelled_dataset[i]**2)/150 - means[i]**2)**(1/2) for i in range(4)]
epsilon = 0.01
qs = [np.quantile(unlabelled_dataset[i], 1-(epsilon**(1/4))/2) for i in range(4)]

def data_to_angle(data_entry, data_type, alpha=0.1): 
    score = (data_entry - means[data_type]) / stdevs[data_type]
    return (1-alpha/2)*(np.pi)*(score/qs[data_type])

angles = np.array([[data_to_angle(unlabelled_dataset[data_type][sample], data_type) for data_type in range(4)] for sample in range(150)])

real_classes = np.zeros(150, dtype = int)
for sample in range(150):
    if dataset[sample][5] == 'Iris-versicolor':
        real_classes[sample] = 1
    if dataset[sample][5] == 'Iris-virginica':
        real_classes[sample] = 2
angles

array([[-4.01208161e-01,  8.94336812e-01, -7.14829457e-01,
        -1.95929807e+00],
       [-5.09156545e-01, -1.08282932e-01, -7.14829457e-01,
        -1.95929807e+00],
       [-6.17104930e-01,  2.92764965e-01, -7.45135963e-01,
        -1.95929807e+00],
       [-6.71079122e-01,  9.22410165e-02, -6.84522950e-01,
        -1.95929807e+00],
       [-4.55182353e-01,  1.09486076e+00, -7.14829457e-01,
        -1.95929807e+00],
       [-2.39285585e-01,  1.69643261e+00, -6.23909938e-01,
        -1.56691528e+00],
       [-6.71079122e-01,  6.93812863e-01, -7.14829457e-01,
        -1.76310667e+00],
       [-4.55182353e-01,  6.93812863e-01, -6.84522950e-01,
        -1.95929807e+00],
       [-7.79027506e-01, -3.08806881e-01, -7.14829457e-01,
        -1.95929807e+00],
       [-5.09156545e-01,  9.22410165e-02, -6.84522950e-01,
        -2.15548946e+00],
       [-2.39285585e-01,  1.29538471e+00, -6.84522950e-01,
        -1.95929807e+00],
       [-5.63130738e-01,  6.93812863e-01, -6.54216444e-01,
      

In [3]:
np.random.seed(14)

num_training_sets = 100
individual_training_size = 30
training_sets = np.zeros((num_training_sets, individual_training_size*3), dtype = int)
for i in range(num_training_sets):
    training_sets[i, : individual_training_size] = np.sort(np.random.choice(50, individual_training_size, False))
    training_sets[i, individual_training_size : individual_training_size*2] = np.sort(np.random.choice(50, individual_training_size, False)) + 50
    training_sets[i, individual_training_size*2 : individual_training_size*3] = np.sort(np.random.choice(50, individual_training_size, False)) + 100
    
testing_sets = []
for training_args in training_sets:
    testing_args = [i for i in range(len(dataset)) if i not in training_args]
    testing_sets.append(testing_args)
testing_sets = np.array(testing_sets)

training_sets = cp.deepcopy(training_sets[77:97])
testing_sets = cp.deepcopy(testing_sets[77:97])

training_sets, testing_sets

(array([[  0,   1,   2, ..., 145, 148, 149],
        [  1,   3,   7, ..., 147, 148, 149],
        [  2,   6,   7, ..., 144, 148, 149],
        ...,
        [  0,   1,   2, ..., 147, 148, 149],
        [  2,   4,   5, ..., 145, 146, 148],
        [  0,   3,   4, ..., 144, 146, 149]]),
 array([[  3,   4,   6, ..., 144, 146, 147],
        [  0,   2,   4, ..., 142, 144, 146],
        [  0,   1,   3, ..., 145, 146, 147],
        ...,
        [  6,  12,  14, ..., 141, 144, 146],
        [  0,   1,   3, ..., 141, 147, 149],
        [  1,   2,   5, ..., 145, 147, 148]]))

In [4]:
#Basic parameterized single site gate
def param_gate(qc, angle, site):
    qc.rx(pi/2, site)
    qc.rz(angle, site)
    qc.rx(pi/2, site)

#Quantum circuit from Fig.7, with input features and parameters
def iris_circuit(qc, inputs, params):
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    qc.cz(0, 1)
    param_gate(qc, params[0], 0)
    param_gate(qc, params[1], 1)
    qc.cz(0, 1)   
    param_gate(qc, inputs[2], 0)
    param_gate(qc, inputs[3], 1)
    qc.cz(0, 1)
    param_gate(qc, params[2], 0)
    param_gate(qc, params[3], 1)
    qc.cz(0, 1)
    
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    qc.cz(0, 1)
    param_gate(qc, params[4], 0)
    param_gate(qc, params[5], 1)
    qc.cz(0, 1) 
    param_gate(qc, inputs[2], 0)
    param_gate(qc, inputs[3], 1)
    qc.cz(0, 1)
    param_gate(qc, params[6], 0)
    param_gate(qc, params[7], 1)
        
#quantum_convolutional_network
def qcnn_circuit(qc, inputs, params):
    
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    param_gate(qc, inputs[2], 2)
    param_gate(qc, inputs[3], 3)
    qc.cz(0, 1)
    qc.cz(1, 2)
    qc.cz(2, 3)

    param_gate(qc, params[0], 0)
    param_gate(qc, params[1], 1)
    param_gate(qc, params[2], 2)
    param_gate(qc, params[3], 3)
    qc.cz(0, 1)
    qc.cz(1, 2)
    qc.cz(2, 3)
    
    qc1, qc2 = QuantumCircuit(1), QuantumCircuit(1)
    param_gate(qc1, params[4], 0)
    param_gate(qc2, params[5], 0)
    custom1 = qc1.to_gate().control(1)
    custom2 = qc2.to_gate().control(1)
    
    qc.append(custom1, [0, 1])
    qc.append(custom2, [3, 2])
    qc.cz(1, 2)

    param_gate(qc, inputs[0], 1)
    param_gate(qc, inputs[1], 2)
    qc.cz(1, 2)

    param_gate(qc, params[6], 1)
    param_gate(qc, params[7], 2)
    qc.cz(1, 2)

    param_gate(qc, inputs[2], 1)
    param_gate(qc, inputs[3], 2)
    qc.cz(1, 2)

    param_gate(qc, params[8], 1)
    param_gate(qc, params[9], 2)


def iris_circuit_extension(qc, inputs, params):
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    qc.cz(0, 1)
    param_gate(qc, params[0], 0)
    param_gate(qc, params[1], 1)
    qc.cz(0, 1)   
    param_gate(qc, inputs[2], 0)
    param_gate(qc, inputs[3], 1)
    qc.cz(0, 1)
    param_gate(qc, params[2], 0)
    param_gate(qc, params[3], 1)
    qc.cz(0, 1)
    
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    qc.cz(0, 1)
    param_gate(qc, params[4], 0)
    param_gate(qc, params[5], 1)
    qc.cz(0, 1) 
    param_gate(qc, inputs[2], 0)
    param_gate(qc, inputs[3], 1)
    qc.cz(0, 1)
    param_gate(qc, params[6], 0)
    param_gate(qc, params[7], 1)
    qc.cz(0, 1)
    
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    qc.cz(0, 1)
    param_gate(qc, params[8], 0)
    param_gate(qc, params[9], 1)
    qc.cz(0, 1) 
    param_gate(qc, inputs[2], 0)
    param_gate(qc, inputs[3], 1)
    qc.cz(0, 1)
    param_gate(qc, params[10], 0)
    param_gate(qc, params[11], 1)

In [5]:
#Returns the guessed class and loss function, given inputs and parameters
def iris_evaluate(inputs, params, backend, real_value, shots = 750):
    qc = QuantumCircuit(2)
    iris_circuit(qc, inputs, params)
    qc.measure_all()
    job_result = execute(qc, backend, shots=shots).result()
    job_counts = job_result.get_counts(qc)
    keys = ['00','01','10','11']
    for key in keys:
        if key not in job_counts:
            job_counts[key] = 0
    count_array = np.array([job_counts['00'], job_counts['01'], job_counts['10'], job_counts['11']])
    exp_array = np.exp(count_array/np.sum(count_array))[:3]
    dominant_class = np.argmax(count_array[:3])
    loss = -np.log(exp_array[real_value]/np.sum(exp_array))
    return dominant_class, loss

def qcnn_evaluate(inputs, params, backend, real_value, shots = 750):
    qc = QuantumCircuit(4, 2)
    qcnn_circuit(qc, inputs, params)
    qc.barrier([0, 1, 2, 3])
    qc.measure([1, 2], [0, 1])
    job_result = execute(qc, backend, shots=shots).result()
    job_counts = job_result.get_counts(qc)
    keys = ['00','01','10','11']
    for key in keys:
        if key not in job_counts:
            job_counts[key] = 0
    count_array = np.array([job_counts['00'], job_counts['01'], job_counts['10'], job_counts['11']])
    exp_array = np.exp(count_array/np.sum(count_array))[:3]
    dominant_class = np.argmax(count_array[:3])
    loss = -np.log(exp_array[real_value]/np.sum(exp_array))
    return dominant_class, loss

def iris_extension_evaluate(inputs, params, backend, real_value, shots = 750):
    qc = QuantumCircuit(2)
    iris_circuit_extension(qc, inputs, params)
    qc.measure_all()
    job_result = execute(qc, backend, shots=shots).result()
    job_counts = job_result.get_counts(qc)
    keys = ['00','01','10','11']
    for key in keys:
        if key not in job_counts:
            job_counts[key] = 0
    count_array = np.array([job_counts['00'], job_counts['01'], job_counts['10'], job_counts['11']])
    exp_array = np.exp(count_array/np.sum(count_array))[:3]
    dominant_class = np.argmax(count_array[:3])
    loss = -np.log(exp_array[real_value]/np.sum(exp_array))
    return dominant_class, loss

backend = Aer.get_backend('qasm_simulator')
starting_params_iris = np.random.rand(8) * 2 * np.pi
starting_params_qcnn = np.random.rand(10) * 2 * np.pi
starting_params_extension = np.random.rand(12) * 2 * np.pi


In [6]:
print("Example eval using iris: ")
target_ind = 33
dclass, loss = iris_evaluate(angles[target_ind], starting_params_iris, backend, real_classes[target_ind])
print("Expected dominant class: {}".format(dclass))
print("Real class: {}".format(real_classes[target_ind]))
print("Loss function: {}".format(loss))

Example eval using iris: 
Expected dominant class: 2
Real class: 0
Loss function: 1.5041036366294918


In [7]:
print("Example eval using qcnn: ")
target_ind = 33
dclass, loss = qcnn_evaluate(angles[target_ind], starting_params_qcnn, backend, real_classes[target_ind])
print("Expected dominant class: {}".format(dclass))
print("Real class: {}".format(real_classes[target_ind]))
print("Loss function: {}".format(loss))

Example eval using qcnn: 
Expected dominant class: 2
Real class: 0
Loss function: 1.070649945749703


In [8]:
print("Example eval using iris_extension: ")
target_ind = 33
dclass, loss = iris_extension_evaluate(angles[target_ind], starting_params_extension, backend, real_classes[target_ind])
print("Expected dominant class: {}".format(dclass))
print("Real class: {}".format(real_classes[target_ind]))
print("Loss function: {}".format(loss))

Example eval using iris_extension: 
Expected dominant class: 2
Real class: 0
Loss function: 1.0799076990518606


In [9]:
test = QuantumCircuit(2)
test_parameters = np.random.rand(8)
test_inputs = angles[125]
test_real_value = real_classes[125]
test_backend = Aer.get_backend('qasm_simulator')
test_shots = 512

iris_circuit(test, test_inputs, test_parameters)
test.measure_all()


test_job_result = execute(test, test_backend, shots=test_shots).result()
test_job_counts = test_job_result.get_counts(test)
keys = ['00','01','10','11']
for key in keys:
    if key not in test_job_counts:
        test_job_counts[key] = 0
        
test_count_array = np.array([test_job_counts['00'], test_job_counts['01'], test_job_counts['10'], test_job_counts['11']])
test_exp_array = np.exp(test_count_array/np.sum(test_count_array))[:3]
test_dominant_class = np.argmax(test_count_array[:3])
test_loss = -np.log(test_exp_array[test_real_value]/np.sum(test_exp_array))


test.draw()

┌─────────┐┌─────────────┐┌─────────┐   ┌─────────┐┌─────────────┐»
   q_0: ┤ Rx(π/2) ├┤ Rz(0.73225) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.95622) ├»
        ├─────────┤├─────────────┤├─────────┤ │ ├─────────┤├─────────────┤»
   q_1: ┤ Rx(π/2) ├┤ Rz(0.29276) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.25606) ├»
        └─────────┘└─────────────┘└─────────┘   └─────────┘└─────────────┘»
meas: 2/══════════════════════════════════════════════════════════════════»
                                                                          »
«        ┌─────────┐   ┌─────────┐┌─────────────┐┌─────────┐   ┌─────────┐»
«   q_0: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.67927) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        ├─────────┤ │ ├─────────┤└┬────────────┤├─────────┤ │ ├─────────┤»
«   q_1: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├─┤ Rz(1.1798) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        └─────────┘   └─────────┘ └────────────┘└─────────┘   └─────────┘»
«meas: 2/═════════════════════════════════════════════════════════════════»
«                                                                         »
«        ┌──────────────┐┌─────────┐   ┌─────────┐┌─────────────┐┌─────────┐   »
«   q_0: ┤ Rz(0.009684) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.73225) ├┤ Rx(π/2) ├─■─»
«        ├─────────────┬┘├─────────┤ │ ├─────────┤├─────────────┤├─────────┤ │ »
«   q_1: ┤ Rz(0.41149) ├─┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.29276) ├┤ Rx(π/2) ├─■─»
«        └─────────────┘ └─────────┘   └─────────┘└─────────────┘└─────────┘   »
«meas: 2/══════════════════════════════════════════════════════════════════════»
«                                                                              »
«        ┌─────────┐┌─────────────┐┌─────────┐   ┌─────────┐┌─────────────┐»
«   q_0: ┤ Rx(π/2) ├┤ Rz(0.27102) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.67927) ├»
«        ├─────────┤├─────────────┤├─────────┤ │ ├─────────┤└┬────────────┤»
«   q_1: ┤ Rx(π/2) ├┤ Rz(0.28464) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├─┤ Rz(1.1798) ├»
«        └─────────┘└─────────────┘└─────────┘   └─────────┘ └────────────┘»
«meas: 2/══════════════════════════════════════════════════════════════════»
«                                                                          »
«        ┌─────────┐   ┌─────────┐┌─────────────┐┌─────────┐ ░ ┌─┐   
«   q_0: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.85256) ├┤ Rx(π/2) ├─░─┤M├───
«        ├─────────┤ │ ├─────────┤├─────────────┤├─────────┤ ░ └╥┘┌─┐
«   q_1: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.19731) ├┤ Rx(π/2) ├─░──╫─┤M├
«        └─────────┘   └─────────┘└─────────────┘└─────────┘ ░  ║ └╥┘
«meas: 2/═══════════════════════════════════════════════════════╩══╩═
«                                                               0  1

In [10]:
a = angles[7]
b = np.random.rand(10) * 2 * np.pi
qc = QuantumCircuit(4, 2)
qcnn_circuit(qc, a, b)
qc.barrier([0, 1, 2, 3])

qc.measure([1, 2], [0, 1])
qc.draw()

┌─────────┐┌──────────────┐┌─────────┐   ┌─────────┐┌────────────┐»
q_0: ┤ Rx(π/2) ├┤ Rz(-0.45518) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(5.4766) ├»
     ├─────────┤├─────────────┬┘├─────────┤ │ └─────────┘└┬─────────┬─┘»
q_1: ┤ Rx(π/2) ├┤ Rz(0.69381) ├─┤ Rx(π/2) ├─■──────■──────┤ Rx(π/2) ├──»
     ├─────────┤├─────────────┴┐├─────────┤        │      └─────────┘  »
q_2: ┤ Rx(π/2) ├┤ Rz(-0.68452) ├┤ Rx(π/2) ├────────■───────────■───────»
     ├─────────┤├─────────────┬┘├─────────┤                    │       »
q_3: ┤ Rx(π/2) ├┤ Rz(-1.9593) ├─┤ Rx(π/2) ├────────────────────■───────»
     └─────────┘└─────────────┘ └─────────┘                            »
c: 2/══════════════════════════════════════════════════════════════════»
                                                                       »
«      ┌─────────┐                                               »
«q_0: ─┤ Rx(π/2) ├──────────────────────■───────────────■────────»
«     ┌┴─────────┴─┐  ┌─────────┐       │        ┌──────┴───────┐»
«q_1: ┤ Rz(1.0411) ├──┤ Rx(π/2) ├───────■──────■─┤ circuit-1766 ├»
«     └┬─────────┬─┘ ┌┴─────────┴─┐┌─────────┐ │ └──────────────┘»
«q_2: ─┤ Rx(π/2) ├───┤ Rz(2.2762) ├┤ Rx(π/2) ├─■────────■────────»
«      ├─────────┤  ┌┴────────────┤├─────────┤          │        »
«q_3: ─┤ Rx(π/2) ├──┤ Rz(0.69381) ├┤ Rx(π/2) ├──────────■────────»
«      └─────────┘  └─────────────┘└─────────┘                   »
«c: 2/═══════════════════════════════════════════════════════════»
«                                                                »
«                                                                            »
«q_0: ───────────────────────────────────────────────────────────────────────»
«                        ┌─────────┐┌──────────────┐┌─────────┐   ┌─────────┐»
«q_1: ─────────────────■─┤ Rx(π/2) ├┤ Rz(-0.45518) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«     ┌──────────────┐ │ ├─────────┤├─────────────┬┘├─────────┤ │ ├─────────┤»
«q_2: ┤ circuit-1767 ├─■─┤ Rx(π/2) ├┤ Rz(0.69381) ├─┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«     └──────┬───────┘   └─────────┘└─────────────┘ └─────────┘   └─────────┘»
«q_3: ───────■───────────────────────────────────────────────────────────────»
«                                                                            »
«c: 2/═══════════════════════════════════════════════════════════════════════»
«                                                                            »
«                                                                          »
«q_0: ─────────────────────────────────────────────────────────────────────»
«     ┌───────────┐ ┌─────────┐   ┌─────────┐┌──────────────┐┌─────────┐   »
«q_1: ┤ Rz(1.073) ├─┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(-0.68452) ├┤ Rx(π/2) ├─■─»
«     ├───────────┴┐├─────────┤ │ ├─────────┤├─────────────┬┘├─────────┤ │ »
«q_2: ┤ Rz(1.5432) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(-1.9593) ├─┤ Rx(π/2) ├─■─»
«     └────────────┘└─────────┘   └─────────┘└─────────────┘ └─────────┘   »
«q_3: ─────────────────────────────────────────────────────────────────────»
«                                                                          »
«c: 2/═════════════════════════════════════════════════════════════════════»
«                                                                          »
«                                          ░       
«q_0: ─────────────────────────────────────░───────
«     ┌─────────┐┌────────────┐┌─────────┐ ░ ┌─┐   
«q_1: ┤ Rx(π/2) ├┤ Rz(3.9659) ├┤ Rx(π/2) ├─░─┤M├───
«     ├─────────┤├────────────┤├─────────┤ ░ └╥┘┌─┐
«q_2: ┤ Rx(π/2) ├┤ Rz(2.4779) ├┤ Rx(π/2) ├─░──╫─┤M├
«     └─────────┘└────────────┘└─────────┘ ░  ║ └╥┘
«q_3: ─────────────────────────────────────░──╫──╫─
«                                          ░  ║  ║ 
«c: 2/════════════════════════════════════════╩══╩═
«                                             0  1

In [11]:
c = angles[54]
d = np.random.rand(12) * 2 * np.pi
qc = QuantumCircuit(2)
iris_circuit_extension(qc, c, d)
qc.measure_all()
qc.draw()

┌─────────┐┌─────────────┐ ┌─────────┐   ┌─────────┐┌────────────┐»
   q_0: ┤ Rx(π/2) ├┤ Rz(0.35443) ├─┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(2.3628) ├»
        ├─────────┤├─────────────┴┐├─────────┤ │ ├─────────┤├────────────┤»
   q_1: ┤ Rx(π/2) ├┤ Rz(-0.50933) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(2.2171) ├»
        └─────────┘└──────────────┘└─────────┘   └─────────┘└────────────┘»
meas: 2/══════════════════════════════════════════════════════════════════»
                                                                          »
«        ┌─────────┐   ┌─────────┐┌─────────────┐┌─────────┐   ┌─────────┐»
«   q_0: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.25498) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        ├─────────┤ │ ├─────────┤├─────────────┤├─────────┤ │ ├─────────┤»
«   q_1: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.59119) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        └─────────┘   └─────────┘└─────────────┘└─────────┘   └─────────┘»
«meas: 2/═════════════════════════════════════════════════════════════════»
«                                                                         »
«        ┌───────────┐ ┌─────────┐   ┌─────────┐┌─────────────┐ ┌─────────┐   »
«   q_0: ┤ Rz(3.883) ├─┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.35443) ├─┤ Rx(π/2) ├─■─»
«        ├───────────┴┐├─────────┤ │ ├─────────┤├─────────────┴┐├─────────┤ │ »
«   q_1: ┤ Rz(4.9694) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(-0.50933) ├┤ Rx(π/2) ├─■─»
«        └────────────┘└─────────┘   └─────────┘└──────────────┘└─────────┘   »
«meas: 2/═════════════════════════════════════════════════════════════════════»
«                                                                             »
«        ┌─────────┐ ┌───────────┐ ┌─────────┐   ┌─────────┐┌─────────────┐»
«   q_0: ┤ Rx(π/2) ├─┤ Rz(4.977) ├─┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.25498) ├»
«        ├─────────┤┌┴───────────┴┐├─────────┤ │ ├─────────┤├─────────────┤»
«   q_1: ┤ Rx(π/2) ├┤ Rz(0.33126) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.59119) ├»
«        └─────────┘└─────────────┘└─────────┘   └─────────┘└─────────────┘»
«meas: 2/══════════════════════════════════════════════════════════════════»
«                                                                          »
«        ┌─────────┐   ┌─────────┐┌────────────┐┌─────────┐   ┌─────────┐»
«   q_0: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(2.4853) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        ├─────────┤ │ ├─────────┤├────────────┤├─────────┤ │ ├─────────┤»
«   q_1: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(3.1283) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        └─────────┘   └─────────┘└────────────┘└─────────┘   └─────────┘»
«meas: 2/════════════════════════════════════════════════════════════════»
«                                                                        »
«        ┌─────────────┐ ┌─────────┐   ┌─────────┐┌────────────┐┌─────────┐   »
«   q_0: ┤ Rz(0.35443) ├─┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(3.9319) ├┤ Rx(π/2) ├─■─»
«        ├─────────────┴┐├─────────┤ │ ├─────────┤├────────────┤├─────────┤ │ »
«   q_1: ┤ Rz(-0.50933) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(2.7096) ├┤ Rx(π/2) ├─■─»
«        └──────────────┘└─────────┘   └─────────┘└────────────┘└─────────┘   »
«meas: 2/═════════════════════════════════════════════════════════════════════»
«                                                                             »
«        ┌─────────┐┌─────────────┐┌─────────┐   ┌─────────┐┌──────────────┐»
«   q_0: ┤ Rx(π/2) ├┤ Rz(0.25498) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.025065) ├»
«        ├─────────┤├─────────────┤├─────────┤ │ ├─────────┤├─────────────┬┘»
«   q_1: ┤ Rx(π/2) ├┤ Rz(0.59119) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.48796) ├─»
«        └─────────┘└─────────────┘└─────────┘   └─────────┘└─────────────┘ »
«meas: 2/═══════════════════════════════════════════════════════════════════»
«                                                                           »
«        ┌─────────┐ ░ ┌─┐   
«   q_0: ┤ Rx(π/2) ├─░─┤M├───
«        ├─────────┤ ░ └╥┘┌─┐
«   q_1: ┤ Rx(π/2) ├─░──╫─┤M├
«        └─────────┘ ░  ║ └╥┘
«meas: 2/═══════════════╩══╩═
«                       0  1

In [12]:
#Returns the average loss function over a certain batch
def evaluate_batch_iris(batch_args, params, backend):
    losses = np.zeros(len(batch_args))
    for ind,arg in enumerate(batch_args):
        dclass, loss = iris_evaluate(angles[arg], params, backend, real_classes[arg])
        losses[ind] = loss
    avgloss = np.mean(losses)
    return avgloss

def evaluate_batch_qcnn(batch_args, params, backend):
    losses = np.zeros(len(batch_args))
    for ind,arg in enumerate(batch_args):
        dclass, loss = qcnn_evaluate(angles[arg], params, backend, real_classes[arg])
        losses[ind] = loss
    avgloss = np.mean(losses)
    return avgloss

def evaluate_batch_extension(batch_args, params, backend):
    losses = np.zeros(len(batch_args))
    for ind,arg in enumerate(batch_args):
        dclass, loss = iris_extension_evaluate(angles[arg], params, backend, real_classes[arg])
        losses[ind] = loss
    avgloss = np.mean(losses)
    return avgloss

def objective_fn(params, algorithm, training_args):
    backend = Aer.get_backend('qasm_simulator')
    batch_args = cp.deepcopy(training_args)
    return algorithm(batch_args, params, backend)

def optimization_cobyla(starting_params, algorithm, training_args):
    result = sp.optimize.minimize(objective_fn, starting_params, args = (algorithm, training_args),  method = 'COBYLA', options = {"maxiter":100000})
    return result.x

def evalutaion_accuracy(testing_args, aalgorithm, point):
    backend = Aer.get_backend('qasm_simulator')
    confusion = np.zeros((3,3), dtype = int)
    for testing_arg in testing_args:
        dclass, loss = aalgorithm(angles[testing_arg], point, backend, real_classes[testing_arg])
        confusion[dclass, real_classes[testing_arg]] += 1
    accuracy = (confusion[0,0] + confusion[1,1] + confusion[2,2]) / np.sum(confusion.flatten())
    return accuracy

In [13]:
parameters_iris = np.array([optimization_cobyla(starting_params_iris, evaluate_batch_iris, i).tolist() for i in training_sets])
parameters_iris

array([[6.75174073, 4.99728838, 6.10855529, 4.42806342, 6.62923756,
        4.36671554, 4.40867654, 3.85433719],
       [6.90668833, 5.72110749, 3.66292907, 4.84203368, 4.57303397,
        5.16692252, 4.34155512, 5.00601267],
       [7.11888998, 6.23895248, 3.8672744 , 4.85436204, 4.93002123,
        4.93765464, 4.67998585, 5.32385657],
       [7.22217882, 6.60363583, 3.83961734, 4.63015816, 5.0757576 ,
        4.97856614, 5.12572506, 6.04061973],
       [7.03217343, 5.26423138, 5.52354233, 4.73229635, 6.39681849,
        5.35665077, 4.49795488, 4.75887917],
       [6.97606273, 6.33314442, 4.04568795, 4.67399781, 5.05089538,
        4.52442407, 4.59851623, 5.20928662],
       [6.76721731, 5.66752138, 3.54060046, 4.94730962, 4.09878609,
        4.66945501, 4.34502922, 4.52428845],
       [7.17639569, 6.47342299, 4.40401628, 4.47229676, 5.32851124,
        3.99957234, 4.74989202, 5.02394667],
       [7.0007927 , 6.41280659, 3.73454962, 4.74758723, 4.88165737,
        4.62878298, 4.753952

In [14]:
parameters_qcnn = np.array([optimization_cobyla(starting_params_qcnn, evaluate_batch_qcnn, i).tolist() for i in training_sets])
parameters_qcnn

array([[ 2.81100353,  5.62072864,  4.64169316,  0.20377758,  3.64829247,
         4.82783444,  4.74243394,  3.76438006,  2.03416592,  3.61565296],
       [ 2.60569533,  5.74804851,  3.90285283,  0.85370158,  3.66216959,
         4.66044489,  4.97349551,  3.20556387,  1.56458422,  3.61729057],
       [ 3.35830429,  6.18968507,  4.08200469,  1.29289159,  4.19344875,
         3.8795767 ,  4.9434887 ,  2.59709703,  1.47804764,  3.3135632 ],
       [ 3.21007499,  5.73091632,  3.96372722,  0.83760598,  4.11981928,
         4.10717566,  5.07267415,  2.6232767 ,  1.70511706,  3.13712106],
       [ 3.23366752,  5.85755478,  4.57534553,  1.23784055,  4.07369217,
         4.39699927,  4.86383765,  3.43131644,  1.46082954,  3.25559693],
       [ 3.04218332,  5.64395934,  4.26920561,  1.14757505,  3.88763363,
         4.13096232,  5.11590371,  2.59469477,  1.73331323,  3.07191004],
       [ 3.5175831 ,  5.94617147,  3.90105938,  1.09310538,  3.84309356,
         4.39531159,  4.92139853,  2.8470028 

In [15]:
parameters_iris_extension = np.array([optimization_cobyla(starting_params_extension, evaluate_batch_extension, i).tolist() for i in training_sets])
parameters_iris_extension

array([[-1.73969958,  1.99619664,  4.85158012,  5.00605015,  4.89287509,
         2.58397679,  4.5435299 ,  1.5925792 ,  3.03085467,  4.90313049,
        -0.05339756,  1.39176206],
       [ 1.86867687,  2.41225182,  5.44606156,  5.17292368,  5.10514979,
         2.13616655,  1.50201212,  1.97819887,  3.77331308,  5.19696884,
         0.55921815,  1.45527698],
       [ 1.63165807,  1.62131726,  5.36503746,  2.07394786,  5.02318469,
         1.657686  ,  1.5094713 , -0.160165  ,  3.83212312,  3.54582005,
         0.14466929,  3.80871572],
       [ 1.76533924,  2.09073035,  5.29156418,  3.35772273,  5.29321342,
         2.28906405,  1.50624952, -0.09475725,  3.71314265,  3.92900833,
         0.4330763 ,  3.47196048],
       [ 1.69796908,  2.175698  ,  5.44041852,  4.95077731,  5.35553287,
         2.07879781,  1.59503407,  1.54024191,  3.6507907 ,  5.75854919,
         0.53405016,  2.19063642],
       [ 2.10616959,  2.36931635,  5.4866975 ,  4.63526292,  5.05244568,
         1.89440186,  

In [16]:
Accuracies_iris = np.array([evalutaion_accuracy(testing_sets[i], iris_evaluate, parameters_iris[i]) for i in range(len(testing_sets))])
Accuracies_iris

array([0.88333333, 0.81666667, 0.88333333, 0.9       , 0.81666667,
       0.8       , 0.81666667, 0.85      , 0.83333333, 0.83333333,
       0.88333333, 0.86666667, 0.91666667, 0.81666667, 0.88333333,
       0.86666667, 0.83333333, 0.86666667, 0.78333333, 0.88333333])

In [17]:
Accuracies_qcnn = np.array([evalutaion_accuracy(testing_sets[i], qcnn_evaluate, parameters_qcnn[i]) for i in range(len(testing_sets))])
Accuracies_qcnn

array([0.8       , 0.81666667, 0.85      , 0.78333333, 0.9       ,
       0.9       , 0.88333333, 0.75      , 0.86666667, 0.9       ,
       0.83333333, 0.86666667, 0.88333333, 0.88333333, 0.86666667,
       0.88333333, 0.83333333, 0.83333333, 0.86666667, 0.91666667])

In [18]:
Accuracies_iris_extension = np.array([evalutaion_accuracy(testing_sets[i], iris_extension_evaluate, parameters_iris_extension[i]) for i in range(len(testing_sets))])
Accuracies_iris_extension

array([0.88333333, 0.9       , 0.83333333, 0.78333333, 0.86666667,
       0.9       , 0.9       , 0.58333333, 0.83333333, 0.83333333,
       0.91666667, 0.88333333, 0.93333333, 0.56666667, 0.85      ,
       0.9       , 0.86666667, 0.9       , 0.83333333, 0.9       ])

In [19]:
print("Accuracy for iris: {}".format(Accuracies_iris.mean()))
print("Accuracy for qcnn: {}".format(Accuracies_qcnn.mean()))
print("Accuracy for iris_extension: {}".format(Accuracies_iris_extension.mean()))

Accuracy for iris: 0.8516666666666668
Accuracy for qcnn: 0.8558333333333333
Accuracy for iris_extension: 0.8433333333333334


In [20]:
print("Accuracy variation for iris: {}".format(Accuracies_iris.std()))
print("Accuracy variation for qcnn: {}".format(Accuracies_qcnn.std()))
print("Accuracy variation for iris_extension: {}".format(Accuracies_iris_extension.std()))

Accuracy variation for iris: 0.03570714214271424
Accuracy variation for qcnn: 0.04225419111362406
Accuracy variation for iris_extension: 0.096234666888347
