In [1]:
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, execute, Aer
from qiskit.compiler import transpile, assemble
from qiskit.tools.jupyter import *
from qiskit.visualization import *
from math import pi, sqrt
import numpy as np
import copy as cp
import scipy as sp
import math

In [2]:
dataset = [['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
['4', '4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
['5', '5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
['6', '5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
['7', '4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
['8', '5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
['9', '4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
['10', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
['11', '5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
['12', '4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
['13', '4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
['15', '5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
['16', '5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
['17', '5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
['18', '5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
['19', '5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
['20', '5.1', '3.8', '1.5', '0.3', 'Iris-setosa'],
['21', '5.4', '3.4', '1.7', '0.2', 'Iris-setosa'],
['22', '5.1', '3.7', '1.5', '0.4', 'Iris-setosa'],
['23', '4.6', '3.6', '1.0', '0.2', 'Iris-setosa'],
['24', '5.1', '3.3', '1.7', '0.5', 'Iris-setosa'],
['25', '4.8', '3.4', '1.9', '0.2', 'Iris-setosa'],
['26', '5.0', '3.0', '1.6', '0.2', 'Iris-setosa'],
['27', '5.0', '3.4', '1.6', '0.4', 'Iris-setosa'],
['28', '5.2', '3.5', '1.5', '0.2', 'Iris-setosa'],
['29', '5.2', '3.4', '1.4', '0.2', 'Iris-setosa'],
['30', '4.7', '3.2', '1.6', '0.2', 'Iris-setosa'],
['31', '4.8', '3.1', '1.6', '0.2', 'Iris-setosa'],
['32', '5.4', '3.4', '1.5', '0.4', 'Iris-setosa'],
['33', '5.2', '4.1', '1.5', '0.1', 'Iris-setosa'],
['34', '5.5', '4.2', '1.4', '0.2', 'Iris-setosa'],
['35', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
['36', '5.0', '3.2', '1.2', '0.2', 'Iris-setosa'],
['37', '5.5', '3.5', '1.3', '0.2', 'Iris-setosa'],
['38', '4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
['39', '4.4', '3.0', '1.3', '0.2', 'Iris-setosa'],
['40', '5.1', '3.4', '1.5', '0.2', 'Iris-setosa'],
['41', '5.0', '3.5', '1.3', '0.3', 'Iris-setosa'],
['42', '4.5', '2.3', '1.3', '0.3', 'Iris-setosa'],
['43', '4.4', '3.2', '1.3', '0.2', 'Iris-setosa'],
['44', '5.0', '3.5', '1.6', '0.6', 'Iris-setosa'],
['45', '5.1', '3.8', '1.9', '0.4', 'Iris-setosa'],
['46', '4.8', '3.0', '1.4', '0.3', 'Iris-setosa'],
['47', '5.1', '3.8', '1.6', '0.2', 'Iris-setosa'],
['48', '4.6', '3.2', '1.4', '0.2', 'Iris-setosa'],
['49', '5.3', '3.7', '1.5', '0.2', 'Iris-setosa'],
['50', '5.0', '3.3', '1.4', '0.2', 'Iris-setosa'],
['51', '7.0', '3.2', '4.7', '1.4', 'Iris-versicolor'],
['52', '6.4', '3.2', '4.5', '1.5', 'Iris-versicolor'],
['53', '6.9', '3.1', '4.9', '1.5', 'Iris-versicolor'],
['54', '5.5', '2.3', '4.0', '1.3', 'Iris-versicolor'],
['55', '6.5', '2.8', '4.6', '1.5', 'Iris-versicolor'],
['56', '5.7', '2.8', '4.5', '1.3', 'Iris-versicolor'],
['57', '6.3', '3.3', '4.7', '1.6', 'Iris-versicolor'],
['58', '4.9', '2.4', '3.3', '1.0', 'Iris-versicolor'],
['59', '6.6', '2.9', '4.6', '1.3', 'Iris-versicolor'],
['60', '5.2', '2.7', '3.9', '1.4', 'Iris-versicolor'],
['61', '5.0', '2.0', '3.5', '1.0', 'Iris-versicolor'],
['62', '5.9', '3.0', '4.2', '1.5', 'Iris-versicolor'],
['63', '6.0', '2.2', '4.0', '1.0', 'Iris-versicolor'],
['64', '6.1', '2.9', '4.7', '1.4', 'Iris-versicolor'],
['65', '5.6', '2.9', '3.6', '1.3', 'Iris-versicolor'],
['66', '6.7', '3.1', '4.4', '1.4', 'Iris-versicolor'],
['67', '5.6', '3.0', '4.5', '1.5', 'Iris-versicolor'],
['68', '5.8', '2.7', '4.1', '1.0', 'Iris-versicolor'],
['69', '6.2', '2.2', '4.5', '1.5', 'Iris-versicolor'],
['70', '5.6', '2.5', '3.9', '1.1', 'Iris-versicolor'],
['71', '5.9', '3.2', '4.8', '1.8', 'Iris-versicolor'],
['72', '6.1', '2.8', '4.0', '1.3', 'Iris-versicolor'],
['73', '6.3', '2.5', '4.9', '1.5', 'Iris-versicolor'],
['74', '6.1', '2.8', '4.7', '1.2', 'Iris-versicolor'],
['75', '6.4', '2.9', '4.3', '1.3', 'Iris-versicolor'],
['76', '6.6', '3.0', '4.4', '1.4', 'Iris-versicolor'],
['77', '6.8', '2.8', '4.8', '1.4', 'Iris-versicolor'],
['78', '6.7', '3.0', '5.0', '1.7', 'Iris-versicolor'],
['79', '6.0', '2.9', '4.5', '1.5', 'Iris-versicolor'],
['80', '5.7', '2.6', '3.5', '1.0', 'Iris-versicolor'],
['81', '5.5', '2.4', '3.8', '1.1', 'Iris-versicolor'],
['82', '5.5', '2.4', '3.7', '1.0', 'Iris-versicolor'],
['83', '5.8', '2.7', '3.9', '1.2', 'Iris-versicolor'],
['84', '6.0', '2.7', '5.1', '1.6', 'Iris-versicolor'],
['85', '5.4', '3.0', '4.5', '1.5', 'Iris-versicolor'],
['86', '6.0', '3.4', '4.5', '1.6', 'Iris-versicolor'],
['87', '6.7', '3.1', '4.7', '1.5', 'Iris-versicolor'],
['88', '6.3', '2.3', '4.4', '1.3', 'Iris-versicolor'],
['89', '5.6', '3.0', '4.1', '1.3', 'Iris-versicolor'],
['90', '5.5', '2.5', '4.0', '1.3', 'Iris-versicolor'],
['91', '5.5', '2.6', '4.4', '1.2', 'Iris-versicolor'],
['92', '6.1', '3.0', '4.6', '1.4', 'Iris-versicolor'],
['93', '5.8', '2.6', '4.0', '1.2', 'Iris-versicolor'],
['94', '5.0', '2.3', '3.3', '1.0', 'Iris-versicolor'],
['95', '5.6', '2.7', '4.2', '1.3', 'Iris-versicolor'],
['96', '5.7', '3.0', '4.2', '1.2', 'Iris-versicolor'],
['97', '5.7', '2.9', '4.2', '1.3', 'Iris-versicolor'],
['98', '6.2', '2.9', '4.3', '1.3', 'Iris-versicolor'],
['99', '5.1', '2.5', '3.0', '1.1', 'Iris-versicolor'],
['100', '5.7', '2.8', '4.1', '1.3', 'Iris-versicolor'],
['101', '6.3', '3.3', '6.0', '2.5', 'Iris-virginica'],
['102', '5.8', '2.7', '5.1', '1.9', 'Iris-virginica'],
['103', '7.1', '3.0', '5.9', '2.1', 'Iris-virginica'],
['104', '6.3', '2.9', '5.6', '1.8', 'Iris-virginica'],
['105', '6.5', '3.0', '5.8', '2.2', 'Iris-virginica'],
['106', '7.6', '3.0', '6.6', '2.1', 'Iris-virginica'],
['107', '4.9', '2.5', '4.5', '1.7', 'Iris-virginica'],
['108', '7.3', '2.9', '6.3', '1.8', 'Iris-virginica'],
['109', '6.7', '2.5', '5.8', '1.8', 'Iris-virginica'],
['110', '7.2', '3.6', '6.1', '2.5', 'Iris-virginica'],
['111', '6.5', '3.2', '5.1', '2.0', 'Iris-virginica'],
['112', '6.4', '2.7', '5.3', '1.9', 'Iris-virginica'],
['113', '6.8', '3.0', '5.5', '2.1', 'Iris-virginica'],
['114', '5.7', '2.5', '5.0', '2.0', 'Iris-virginica'],
['115', '5.8', '2.8', '5.1', '2.4', 'Iris-virginica'],
['116', '6.4', '3.2', '5.3', '2.3', 'Iris-virginica'],
['117', '6.5', '3.0', '5.5', '1.8', 'Iris-virginica'],
['118', '7.7', '3.8', '6.7', '2.2', 'Iris-virginica'],
['119', '7.7', '2.6', '6.9', '2.3', 'Iris-virginica'],
['120', '6.0', '2.2', '5.0', '1.5', 'Iris-virginica'],
['121', '6.9', '3.2', '5.7', '2.3', 'Iris-virginica'],
['122', '5.6', '2.8', '4.9', '2.0', 'Iris-virginica'],
['123', '7.7', '2.8', '6.7', '2.0', 'Iris-virginica'],
['124', '6.3', '2.7', '4.9', '1.8', 'Iris-virginica'],
['125', '6.7', '3.3', '5.7', '2.1', 'Iris-virginica'],
['126', '7.2', '3.2', '6.0', '1.8', 'Iris-virginica'],
['127', '6.2', '2.8', '4.8', '1.8', 'Iris-virginica'],
['128', '6.1', '3.0', '4.9', '1.8', 'Iris-virginica'],
['129', '6.4', '2.8', '5.6', '2.1', 'Iris-virginica'],
['130', '7.2', '3.0', '5.8', '1.6', 'Iris-virginica'],
['131', '7.4', '2.8', '6.1', '1.9', 'Iris-virginica'],
['132', '7.9', '3.8', '6.4', '2.0', 'Iris-virginica'],
['133', '6.4', '2.8', '5.6', '2.2', 'Iris-virginica'],
['134', '6.3', '2.8', '5.1', '1.5', 'Iris-virginica'],
['135', '6.1', '2.6', '5.6', '1.4', 'Iris-virginica'],
['136', '7.7', '3.0', '6.1', '2.3', 'Iris-virginica'],
['137', '6.3', '3.4', '5.6', '2.4', 'Iris-virginica'],
['138', '6.4', '3.1', '5.5', '1.8', 'Iris-virginica'],
['139', '6.0', '3.0', '4.8', '1.8', 'Iris-virginica'],
['140', '6.9', '3.1', '5.4', '2.1', 'Iris-virginica'],
['141', '6.7', '3.1', '5.6', '2.4', 'Iris-virginica'],
['142', '6.9', '3.1', '5.1', '2.3', 'Iris-virginica'],
['143', '5.8', '2.7', '5.1', '1.9', 'Iris-virginica'],
['144', '6.8', '3.2', '5.9', '2.3', 'Iris-virginica'],
['145', '6.7', '3.3', '5.7', '2.5', 'Iris-virginica'],
['146', '6.7', '3.0', '5.2', '2.3', 'Iris-virginica'],
['147', '6.3', '2.5', '5.0', '1.9', 'Iris-virginica'],
['148', '6.5', '3.0', '5.2', '2.0', 'Iris-virginica'],
['149', '6.2', '3.4', '5.4', '2.3', 'Iris-virginica'],
['150', '5.9', '3.0', '5.1', '1.8', 'Iris-virginica']]

unlabelled_dataset = [np.array([float(data[1]) for data in dataset]), np.array([float(data[2]) for data in dataset]), 
                      np.array([float(data[3]) for data in dataset]), np.array([float(data[4]) for data in dataset])]

means = [sum(unlabelled_dataset[i])/150 for i in range(4)]
stdevs = [(sum(unlabelled_dataset[i]**2)/150 - means[i]**2)**(1/2) for i in range(4)]
epsilon = 0.01
qs = [np.quantile(unlabelled_dataset[i], 1-(epsilon**(1/4))/2) for i in range(4)]

def data_to_angle(data_entry, data_type, alpha=0.1): 
    score = (data_entry - means[data_type]) / stdevs[data_type]
    return (1-alpha/2)*(np.pi)*(score/qs[data_type])

angles = np.array([[data_to_angle(unlabelled_dataset[data_type][sample], data_type) for data_type in range(4)] for sample in range(150)])

real_classes = np.zeros(150, dtype = int)
for sample in range(150):
    if dataset[sample][5] == 'Iris-versicolor':
        real_classes[sample] = 1
    if dataset[sample][5] == 'Iris-virginica':
        real_classes[sample] = 2
angles

array([[-4.01208161e-01,  8.94336812e-01, -7.14829457e-01,
        -1.95929807e+00],
       [-5.09156545e-01, -1.08282932e-01, -7.14829457e-01,
        -1.95929807e+00],
       [-6.17104930e-01,  2.92764965e-01, -7.45135963e-01,
        -1.95929807e+00],
       [-6.71079122e-01,  9.22410165e-02, -6.84522950e-01,
        -1.95929807e+00],
       [-4.55182353e-01,  1.09486076e+00, -7.14829457e-01,
        -1.95929807e+00],
       [-2.39285585e-01,  1.69643261e+00, -6.23909938e-01,
        -1.56691528e+00],
       [-6.71079122e-01,  6.93812863e-01, -7.14829457e-01,
        -1.76310667e+00],
       [-4.55182353e-01,  6.93812863e-01, -6.84522950e-01,
        -1.95929807e+00],
       [-7.79027506e-01, -3.08806881e-01, -7.14829457e-01,
        -1.95929807e+00],
       [-5.09156545e-01,  9.22410165e-02, -6.84522950e-01,
        -2.15548946e+00],
       [-2.39285585e-01,  1.29538471e+00, -6.84522950e-01,
        -1.95929807e+00],
       [-5.63130738e-01,  6.93812863e-01, -6.54216444e-01,
      

In [3]:
np.random.seed(14)

num_training_sets = 10
individual_training_size = 30
training_sets = np.zeros((num_training_sets, individual_training_size*3), dtype = int)
for i in range(num_training_sets):
    training_sets[i, : individual_training_size] = np.sort(np.random.choice(50, individual_training_size, False))
    training_sets[i, individual_training_size : individual_training_size*2] = np.sort(np.random.choice(50, individual_training_size, False)) + 50
    training_sets[i, individual_training_size*2 : individual_training_size*3] = np.sort(np.random.choice(50, individual_training_size, False)) + 100
    
testing_sets = []
for training_args in training_sets:
    testing_args = [i for i in range(len(dataset)) if i not in training_args]
    testing_sets.append(testing_args)
testing_sets = np.array(testing_sets)

training_sets, testing_sets

(array([[  1,   2,   3,   5,   6,   8,   9,  11,  14,  15,  17,  18,  19,
          20,  21,  27,  29,  30,  31,  34,  35,  36,  37,  39,  40,  44,
          45,  47,  48,  49,  50,  52,  56,  57,  58,  62,  68,  69,  72,
          73,  74,  75,  76,  77,  79,  80,  81,  82,  83,  84,  85,  86,
          88,  89,  90,  92,  93,  96,  98,  99, 102, 103, 105, 106, 107,
         109, 110, 113, 114, 117, 118, 119, 120, 121, 123, 124, 125, 127,
         129, 130, 132, 135, 136, 137, 140, 141, 142, 144, 146, 148],
        [  1,   2,   5,   6,   8,  10,  12,  13,  15,  16,  17,  18,  21,
          22,  23,  24,  26,  27,  30,  31,  32,  33,  34,  37,  38,  40,
          43,  44,  45,  46,  53,  54,  55,  59,  60,  61,  63,  64,  65,
          67,  69,  70,  71,  73,  74,  75,  77,  78,  82,  83,  84,  86,
          87,  89,  90,  92,  94,  95,  96,  97, 102, 103, 105, 106, 109,
         110, 113, 114, 115, 116, 118, 119, 121, 122, 123, 124, 125, 126,
         127, 128, 130, 131, 132, 134, 136

In [4]:
#Basic parameterized single site gate
def param_gate(qc, angle, site):
    qc.rx(pi/2, site)
    qc.rz(angle, site)
    qc.rx(pi/2, site)

#Quantum circuit from Fig.7, with input features and parameters
def iris_circuit(qc, inputs, params):
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    qc.cz(0, 1)
    param_gate(qc, params[0], 0)
    param_gate(qc, params[1], 1)
    qc.cz(0, 1)   
    param_gate(qc, inputs[2], 0)
    param_gate(qc, inputs[3], 1)
    qc.cz(0, 1)
    param_gate(qc, params[2], 0)
    param_gate(qc, params[3], 1)
    qc.cz(0, 1)
    
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    qc.cz(0, 1)
    param_gate(qc, params[4], 0)
    param_gate(qc, params[5], 1)
    qc.cz(0, 1) 
    param_gate(qc, inputs[2], 0)
    param_gate(qc, inputs[3], 1)
    qc.cz(0, 1)
    param_gate(qc, params[6], 0)
    param_gate(qc, params[7], 1)
        
#quantum_convolutional_network
def qcnn_circuit(qc, inputs, params):
    
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    param_gate(qc, inputs[2], 2)
    param_gate(qc, inputs[3], 3)
    qc.cz(0, 1)
    qc.cz(1, 2)
    qc.cz(2, 3)

    param_gate(qc, params[0], 0)
    param_gate(qc, params[1], 1)
    param_gate(qc, params[2], 2)
    param_gate(qc, params[3], 3)
    qc.cz(0, 1)
    qc.cz(1, 2)
    qc.cz(2, 3)
    
    qc1, qc2 = QuantumCircuit(1), QuantumCircuit(1)
    param_gate(qc1, params[4], 0)
    param_gate(qc2, params[5], 0)
    custom1 = qc1.to_gate().control(1)
    custom2 = qc2.to_gate().control(1)
    
    qc.append(custom1, [0, 1])
    qc.append(custom2, [3, 2])
    qc.cz(1, 2)

    param_gate(qc, inputs[0], 1)
    param_gate(qc, inputs[1], 2)
    qc.cz(1, 2)

    param_gate(qc, params[6], 1)
    param_gate(qc, params[7], 2)
    qc.cz(1, 2)

    param_gate(qc, inputs[2], 1)
    param_gate(qc, inputs[3], 2)
    qc.cz(1, 2)

    param_gate(qc, params[8], 1)
    param_gate(qc, params[9], 2)


def iris_circuit_extension(qc, inputs, params):
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    qc.cz(0, 1)
    param_gate(qc, params[0], 0)
    param_gate(qc, params[1], 1)
    qc.cz(0, 1)   
    param_gate(qc, inputs[2], 0)
    param_gate(qc, inputs[3], 1)
    qc.cz(0, 1)
    param_gate(qc, params[2], 0)
    param_gate(qc, params[3], 1)
    qc.cz(0, 1)
    
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    qc.cz(0, 1)
    param_gate(qc, params[4], 0)
    param_gate(qc, params[5], 1)
    qc.cz(0, 1) 
    param_gate(qc, inputs[2], 0)
    param_gate(qc, inputs[3], 1)
    qc.cz(0, 1)
    param_gate(qc, params[6], 0)
    param_gate(qc, params[7], 1)
    qc.cz(0, 1)
    
    param_gate(qc, inputs[0], 0)
    param_gate(qc, inputs[1], 1)
    qc.cz(0, 1)
    param_gate(qc, params[8], 0)
    param_gate(qc, params[9], 1)
    qc.cz(0, 1) 
    param_gate(qc, inputs[2], 0)
    param_gate(qc, inputs[3], 1)
    qc.cz(0, 1)
    param_gate(qc, params[10], 0)
    param_gate(qc, params[11], 1)

In [5]:
#Returns the guessed class and loss function, given inputs and parameters
def iris_evaluate(inputs, params, backend, real_value, shots = 750):
    qc = QuantumCircuit(2)
    iris_circuit(qc, inputs, params)
    qc.measure_all()
    job_result = execute(qc, backend, shots=shots).result()
    job_counts = job_result.get_counts(qc)
    keys = ['00','01','10','11']
    for key in keys:
        if key not in job_counts:
            job_counts[key] = 0
    count_array = np.array([job_counts['00'], job_counts['01'], job_counts['10'], job_counts['11']])
    exp_array = np.exp(count_array/np.sum(count_array))[:3]
    dominant_class = np.argmax(count_array[:3])
    loss = -np.log(exp_array[real_value]/np.sum(exp_array))
    return dominant_class, loss

def qcnn_evaluate(inputs, params, backend, real_value, shots = 750):
    qc = QuantumCircuit(4, 2)
    qcnn_circuit(qc, inputs, params)
    qc.barrier([0, 1, 2, 3])
    qc.measure([1, 2], [0, 1])
    job_result = execute(qc, backend, shots=shots).result()
    job_counts = job_result.get_counts(qc)
    keys = ['00','01','10','11']
    for key in keys:
        if key not in job_counts:
            job_counts[key] = 0
    count_array = np.array([job_counts['00'], job_counts['01'], job_counts['10'], job_counts['11']])
    exp_array = np.exp(count_array/np.sum(count_array))[:3]
    dominant_class = np.argmax(count_array[:3])
    loss = -np.log(exp_array[real_value]/np.sum(exp_array))
    return dominant_class, loss

def iris_extension_evaluate(inputs, params, backend, real_value, shots = 750):
    qc = QuantumCircuit(2)
    iris_circuit_extension(qc, inputs, params)
    qc.measure_all()
    job_result = execute(qc, backend, shots=shots).result()
    job_counts = job_result.get_counts(qc)
    keys = ['00','01','10','11']
    for key in keys:
        if key not in job_counts:
            job_counts[key] = 0
    count_array = np.array([job_counts['00'], job_counts['01'], job_counts['10'], job_counts['11']])
    exp_array = np.exp(count_array/np.sum(count_array))[:3]
    dominant_class = np.argmax(count_array[:3])
    loss = -np.log(exp_array[real_value]/np.sum(exp_array))
    return dominant_class, loss

backend = Aer.get_backend('qasm_simulator')
starting_params_iris = np.random.rand(8) * 2 * np.pi
starting_params_qcnn = np.random.rand(10) * 2 * np.pi
starting_params_extension = np.random.rand(12) * 2 * np.pi


In [6]:
print("Example eval using iris: ")
target_ind = 33
dclass, loss = iris_evaluate(angles[target_ind], starting_params_iris, backend, real_classes[target_ind])
print("Expected dominant class: {}".format(dclass))
print("Real class: {}".format(real_classes[target_ind]))
print("Loss function: {}".format(loss))

Example eval using iris: 
Expected dominant class: 2
Real class: 0
Loss function: 1.2042367794890467


In [7]:
print("Example eval using qcnn: ")
target_ind = 33
dclass, loss = qcnn_evaluate(angles[target_ind], starting_params_qcnn, backend, real_classes[target_ind])
print("Expected dominant class: {}".format(dclass))
print("Real class: {}".format(real_classes[target_ind]))
print("Loss function: {}".format(loss))

Example eval using qcnn: 
Expected dominant class: 0
Real class: 0
Loss function: 1.0300629984219605


In [8]:
print("Example eval using iris_extension: ")
target_ind = 33
dclass, loss = iris_extension_evaluate(angles[target_ind], starting_params_extension, backend, real_classes[target_ind])
print("Expected dominant class: {}".format(dclass))
print("Real class: {}".format(real_classes[target_ind]))
print("Loss function: {}".format(loss))

Example eval using iris_extension: 
Expected dominant class: 0
Real class: 0
Loss function: 0.9447808116293155


In [9]:
test = QuantumCircuit(2)
test_parameters = np.random.rand(8)
test_inputs = angles[125]
test_real_value = real_classes[125]
test_backend = Aer.get_backend('qasm_simulator')
test_shots = 512

iris_circuit(test, test_inputs, test_parameters)
test.measure_all()


test_job_result = execute(test, test_backend, shots=test_shots).result()
test_job_counts = test_job_result.get_counts(test)
keys = ['00','01','10','11']
for key in keys:
    if key not in test_job_counts:
        test_job_counts[key] = 0
        
test_count_array = np.array([test_job_counts['00'], test_job_counts['01'], test_job_counts['10'], test_job_counts['11']])
test_exp_array = np.exp(test_count_array/np.sum(test_count_array))[:3]
test_dominant_class = np.argmax(test_count_array[:3])
test_loss = -np.log(test_exp_array[test_real_value]/np.sum(test_exp_array))


test.draw()

┌─────────┐┌─────────────┐┌─────────┐   ┌─────────┐┌─────────────┐»
   q_0: ┤ Rx(π/2) ├┤ Rz(0.73225) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.65368) ├»
        ├─────────┤├─────────────┤├─────────┤ │ ├─────────┤├─────────────┤»
   q_1: ┤ Rx(π/2) ├┤ Rz(0.29276) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.40056) ├»
        └─────────┘└─────────────┘└─────────┘   └─────────┘└─────────────┘»
meas: 2/══════════════════════════════════════════════════════════════════»
                                                                          »
«        ┌─────────┐   ┌─────────┐┌─────────────┐┌─────────┐   ┌─────────┐»
«   q_0: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.67927) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        ├─────────┤ │ ├─────────┤└┬────────────┤├─────────┤ │ ├─────────┤»
«   q_1: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├─┤ Rz(1.1798) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        └─────────┘   └─────────┘ └────────────┘└─────────┘   └─────────┘»
«meas: 2/═════════════════════════════════════════════════════════════════»
«                                                                         »
«        ┌─────────────┐┌─────────┐   ┌─────────┐┌─────────────┐┌─────────┐   »
«   q_0: ┤ Rz(0.61944) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.73225) ├┤ Rx(π/2) ├─■─»
«        ├─────────────┤├─────────┤ │ ├─────────┤├─────────────┤├─────────┤ │ »
«   q_1: ┤ Rz(0.23292) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.29276) ├┤ Rx(π/2) ├─■─»
«        └─────────────┘└─────────┘   └─────────┘└─────────────┘└─────────┘   »
«meas: 2/═════════════════════════════════════════════════════════════════════»
«                                                                             »
«        ┌─────────┐┌─────────────┐┌─────────┐   ┌─────────┐┌─────────────┐»
«   q_0: ┤ Rx(π/2) ├┤ Rz(0.69589) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.67927) ├»
«        ├─────────┤├─────────────┤├─────────┤ │ ├─────────┤└┬────────────┤»
«   q_1: ┤ Rx(π/2) ├┤ Rz(0.61689) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├─┤ Rz(1.1798) ├»
«        └─────────┘└─────────────┘└─────────┘   └─────────┘ └────────────┘»
«meas: 2/══════════════════════════════════════════════════════════════════»
«                                                                          »
«        ┌─────────┐   ┌─────────┐┌─────────────┐┌─────────┐ ░ ┌─┐   
«   q_0: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.46503) ├┤ Rx(π/2) ├─░─┤M├───
«        ├─────────┤ │ ├─────────┤├─────────────┤├─────────┤ ░ └╥┘┌─┐
«   q_1: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.87123) ├┤ Rx(π/2) ├─░──╫─┤M├
«        └─────────┘   └─────────┘└─────────────┘└─────────┘ ░  ║ └╥┘
«meas: 2/═══════════════════════════════════════════════════════╩══╩═
«                                                               0  1

In [10]:
a = angles[7]
b = np.random.rand(10) * 2 * np.pi
qc = QuantumCircuit(4, 2)
qcnn_circuit(qc, a, b)
qc.barrier([0, 1, 2, 3])

qc.measure([1, 2], [0, 1])
qc.draw()

┌─────────┐┌──────────────┐┌─────────┐   ┌─────────┐┌────────────┐»
q_0: ┤ Rx(π/2) ├┤ Rz(-0.45518) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(6.2144) ├»
     ├─────────┤├─────────────┬┘├─────────┤ │ └─────────┘└┬─────────┬─┘»
q_1: ┤ Rx(π/2) ├┤ Rz(0.69381) ├─┤ Rx(π/2) ├─■──────■──────┤ Rx(π/2) ├──»
     ├─────────┤├─────────────┴┐├─────────┤        │      └─────────┘  »
q_2: ┤ Rx(π/2) ├┤ Rz(-0.68452) ├┤ Rx(π/2) ├────────■───────────■───────»
     ├─────────┤├─────────────┬┘├─────────┤                    │       »
q_3: ┤ Rx(π/2) ├┤ Rz(-1.9593) ├─┤ Rx(π/2) ├────────────────────■───────»
     └─────────┘└─────────────┘ └─────────┘                            »
c: 2/══════════════════════════════════════════════════════════════════»
                                                                       »
«       ┌─────────┐                                              »
«q_0: ──┤ Rx(π/2) ├─────────────────────■───────────────■────────»
«     ┌─┴─────────┴─┐ ┌─────────┐       │        ┌──────┴───────┐»
«q_1: ┤ Rz(0.81518) ├─┤ Rx(π/2) ├───────■──────■─┤ circuit-1766 ├»
«     └─┬─────────┬─┘┌┴─────────┴─┐┌─────────┐ │ └──────────────┘»
«q_2: ──┤ Rx(π/2) ├──┤ Rz(2.7847) ├┤ Rx(π/2) ├─■────────■────────»
«       ├─────────┤  ├────────────┤├─────────┤          │        »
«q_3: ──┤ Rx(π/2) ├──┤ Rz(4.0683) ├┤ Rx(π/2) ├──────────■────────»
«       └─────────┘  └────────────┘└─────────┘                   »
«c: 2/═══════════════════════════════════════════════════════════»
«                                                                »
«                                                                            »
«q_0: ───────────────────────────────────────────────────────────────────────»
«                        ┌─────────┐┌──────────────┐┌─────────┐   ┌─────────┐»
«q_1: ─────────────────■─┤ Rx(π/2) ├┤ Rz(-0.45518) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«     ┌──────────────┐ │ ├─────────┤├─────────────┬┘├─────────┤ │ ├─────────┤»
«q_2: ┤ circuit-1767 ├─■─┤ Rx(π/2) ├┤ Rz(0.69381) ├─┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«     └──────┬───────┘   └─────────┘└─────────────┘ └─────────┘   └─────────┘»
«q_3: ───────■───────────────────────────────────────────────────────────────»
«                                                                            »
«c: 2/═══════════════════════════════════════════════════════════════════════»
«                                                                            »
«                                                                          »
«q_0: ─────────────────────────────────────────────────────────────────────»
«     ┌────────────┐┌─────────┐   ┌─────────┐┌──────────────┐┌─────────┐   »
«q_1: ┤ Rz(4.6475) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(-0.68452) ├┤ Rx(π/2) ├─■─»
«     ├────────────┤├─────────┤ │ ├─────────┤├─────────────┬┘├─────────┤ │ »
«q_2: ┤ Rz(4.8834) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(-1.9593) ├─┤ Rx(π/2) ├─■─»
«     └────────────┘└─────────┘   └─────────┘└─────────────┘ └─────────┘   »
«q_3: ─────────────────────────────────────────────────────────────────────»
«                                                                          »
«c: 2/═════════════════════════════════════════════════════════════════════»
«                                                                          »
«                                          ░       
«q_0: ─────────────────────────────────────░───────
«     ┌─────────┐┌────────────┐┌─────────┐ ░ ┌─┐   
«q_1: ┤ Rx(π/2) ├┤ Rz(2.2326) ├┤ Rx(π/2) ├─░─┤M├───
«     ├─────────┤├───────────┬┘├─────────┤ ░ └╥┘┌─┐
«q_2: ┤ Rx(π/2) ├┤ Rz(4.808) ├─┤ Rx(π/2) ├─░──╫─┤M├
«     └─────────┘└───────────┘ └─────────┘ ░  ║ └╥┘
«q_3: ─────────────────────────────────────░──╫──╫─
«                                          ░  ║  ║ 
«c: 2/════════════════════════════════════════╩══╩═
«                                             0  1

In [11]:
c = angles[54]
d = np.random.rand(12) * 2 * np.pi
qc = QuantumCircuit(2)
iris_circuit_extension(qc, c, d)
qc.measure_all()
qc.draw()

┌─────────┐┌─────────────┐ ┌─────────┐   ┌─────────┐┌────────────┐»
   q_0: ┤ Rx(π/2) ├┤ Rz(0.35443) ├─┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(2.6208) ├»
        ├─────────┤├─────────────┴┐├─────────┤ │ ├─────────┤├───────────┬┘»
   q_1: ┤ Rx(π/2) ├┤ Rz(-0.50933) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(1.961) ├─»
        └─────────┘└──────────────┘└─────────┘   └─────────┘└───────────┘ »
meas: 2/══════════════════════════════════════════════════════════════════»
                                                                          »
«        ┌─────────┐   ┌─────────┐┌─────────────┐┌─────────┐   ┌─────────┐»
«   q_0: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.25498) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        ├─────────┤ │ ├─────────┤├─────────────┤├─────────┤ │ ├─────────┤»
«   q_1: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.59119) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        └─────────┘   └─────────┘└─────────────┘└─────────┘   └─────────┘»
«meas: 2/═════════════════════════════════════════════════════════════════»
«                                                                         »
«        ┌────────────┐┌─────────┐   ┌─────────┐┌─────────────┐ ┌─────────┐   »
«   q_0: ┤ Rz(3.8947) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.35443) ├─┤ Rx(π/2) ├─■─»
«        ├────────────┤├─────────┤ │ ├─────────┤├─────────────┴┐├─────────┤ │ »
«   q_1: ┤ Rz(3.7899) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(-0.50933) ├┤ Rx(π/2) ├─■─»
«        └────────────┘└─────────┘   └─────────┘└──────────────┘└─────────┘   »
«meas: 2/═════════════════════════════════════════════════════════════════════»
«                                                                             »
«        ┌─────────┐┌────────────┐┌─────────┐   ┌─────────┐┌─────────────┐»
«   q_0: ┤ Rx(π/2) ├┤ Rz(3.3899) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.25498) ├»
«        ├─────────┤├────────────┤├─────────┤ │ ├─────────┤├─────────────┤»
«   q_1: ┤ Rx(π/2) ├┤ Rz(2.7391) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.59119) ├»
«        └─────────┘└────────────┘└─────────┘   └─────────┘└─────────────┘»
«meas: 2/═════════════════════════════════════════════════════════════════»
«                                                                         »
«        ┌─────────┐   ┌─────────┐┌────────────┐┌─────────┐   ┌─────────┐»
«   q_0: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(3.6455) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        ├─────────┤ │ ├─────────┤├────────────┤├─────────┤ │ ├─────────┤»
«   q_1: ┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(5.3033) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├»
«        └─────────┘   └─────────┘└────────────┘└─────────┘   └─────────┘»
«meas: 2/════════════════════════════════════════════════════════════════»
«                                                                        »
«        ┌─────────────┐ ┌─────────┐   ┌─────────┐┌─────────────┐┌─────────┐   »
«   q_0: ┤ Rz(0.35443) ├─┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.18543) ├┤ Rx(π/2) ├─■─»
«        ├─────────────┴┐├─────────┤ │ ├─────────┤└┬────────────┤├─────────┤ │ »
«   q_1: ┤ Rz(-0.50933) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├─┤ Rz(2.6023) ├┤ Rx(π/2) ├─■─»
«        └──────────────┘└─────────┘   └─────────┘ └────────────┘└─────────┘   »
«meas: 2/══════════════════════════════════════════════════════════════════════»
«                                                                              »
«        ┌─────────┐┌─────────────┐┌─────────┐   ┌─────────┐ ┌────────────┐»
«   q_0: ┤ Rx(π/2) ├┤ Rz(0.25498) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├─┤ Rz(1.6188) ├»
«        ├─────────┤├─────────────┤├─────────┤ │ ├─────────┤┌┴────────────┤»
«   q_1: ┤ Rx(π/2) ├┤ Rz(0.59119) ├┤ Rx(π/2) ├─■─┤ Rx(π/2) ├┤ Rz(0.94979) ├»
«        └─────────┘└─────────────┘└─────────┘   └─────────┘└─────────────┘»
«meas: 2/══════════════════════════════════════════════════════════════════»
«                                                                          »
«        ┌─────────┐ ░ ┌─┐   
«   q_0: ┤ Rx(π/2) ├─░─┤M├───
«        ├─────────┤ ░ └╥┘┌─┐
«   q_1: ┤ Rx(π/2) ├─░──╫─┤M├
«        └─────────┘ ░  ║ └╥┘
«meas: 2/═══════════════╩══╩═
«                       0  1

In [12]:
#Returns the average loss function over a certain batch
def evaluate_batch_iris(batch_args, params, backend):
    losses = np.zeros(len(batch_args))
    for ind,arg in enumerate(batch_args):
        dclass, loss = iris_evaluate(angles[arg], params, backend, real_classes[arg])
        losses[ind] = loss
    avgloss = np.mean(losses)
    return avgloss

def evaluate_batch_qcnn(batch_args, params, backend):
    losses = np.zeros(len(batch_args))
    for ind,arg in enumerate(batch_args):
        dclass, loss = qcnn_evaluate(angles[arg], params, backend, real_classes[arg])
        losses[ind] = loss
    avgloss = np.mean(losses)
    return avgloss

def evaluate_batch_extension(batch_args, params, backend):
    losses = np.zeros(len(batch_args))
    for ind,arg in enumerate(batch_args):
        dclass, loss = iris_extension_evaluate(angles[arg], params, backend, real_classes[arg])
        losses[ind] = loss
    avgloss = np.mean(losses)
    return avgloss

def objective_fn(params, algorithm, training_args):
    backend = Aer.get_backend('qasm_simulator')
    batch_args = cp.deepcopy(training_args)
    return algorithm(batch_args, params, backend)

def optimization_cobyla(starting_params, algorithm, training_args):
    result = sp.optimize.minimize(objective_fn, starting_params, args = (algorithm, training_args),  method = 'COBYLA', options = {"maxiter":100000})
    return result.x

def evalutaion_accuracy(testing_args, aalgorithm, point):
    backend = Aer.get_backend('qasm_simulator')
    confusion = np.zeros((3,3), dtype = int)
    for testing_arg in testing_args:
        dclass, loss = aalgorithm(angles[testing_arg], point, backend, real_classes[testing_arg])
        confusion[dclass, real_classes[testing_arg]] += 1
    accuracy = (confusion[0,0] + confusion[1,1] + confusion[2,2]) / np.sum(confusion.flatten())
    return accuracy

In [13]:
parameters_iris = np.array([optimization_cobyla(starting_params_iris, evaluate_batch_iris, i).tolist() for i in training_sets])
parameters_iris

array([[ 4.82703196,  0.5283056 ,  4.18073433,  4.98806407,  2.77035532,
         2.74470657,  6.5024206 ,  2.83024658],
       [ 4.69695348,  0.2995683 ,  4.48034625,  5.93910737,  3.17414593,
         4.09774978,  6.649637  ,  3.4256911 ],
       [ 4.91395182,  0.63820518,  4.79273817,  5.50864941,  3.37224484,
         3.6689387 ,  6.53636887,  3.58591011],
       [ 4.72668593,  0.59828667,  4.8660193 ,  4.78373707,  3.43105234,
         2.70755454,  6.43337796,  3.08589607],
       [ 4.52906833,  0.06971434,  4.67760043,  5.04260367,  3.43314414,
         3.52909075,  6.39583013,  3.33644702],
       [ 4.856865  ,  0.40945458,  4.65116597,  5.16565219,  3.32774291,
         2.98346796,  6.57372169,  2.98450479],
       [ 4.55522855, -0.16641473,  5.34378108,  4.68062093,  3.99939615,
         3.0502586 ,  6.09490831,  3.23116085],
       [ 4.74686051,  0.36610528,  4.74849986,  5.27039818,  3.37064608,
         3.35812579,  6.51659808,  3.30054844],
       [ 4.70849783,  0.52939854

In [14]:
parameters_qcnn = np.array([optimization_cobyla(starting_params_qcnn, evaluate_batch_qcnn, i).tolist() for i in training_sets])
parameters_qcnn

array([[ 4.20385149,  3.6567134 ,  2.26044396,  4.23159378,  0.81505046,
         3.31229454,  1.25378937,  3.42939009,  2.90401874,  5.0653045 ],
       [ 5.97620039, -0.51605761, -0.17406331,  1.97772248,  1.77482054,
         5.02938039,  1.2882231 ,  3.96459306,  4.357817  ,  2.03867801],
       [ 4.84639218,  3.400327  ,  1.98663544,  4.73663522,  1.27606674,
         3.82078329,  1.33793281,  3.12834955,  1.9350945 ,  5.7240384 ],
       [ 5.75375697,  2.03005729,  0.84814027,  5.31110263,  1.24208977,
         5.39524239,  2.33386921,  2.71619531,  4.09630991,  3.41974693],
       [ 6.37824885,  2.05641477,  2.08219179,  4.84842653,  0.22522618,
         5.34362808,  2.75630189,  3.81398046,  3.76389045,  4.62373993],
       [ 4.41366862,  3.71622181,  2.22309221,  4.23265707, -0.31898525,
         3.61089955,  1.23678462,  4.01254488,  3.00194227,  4.66308611],
       [ 6.31318104,  2.16597049,  2.06067883,  4.53796387,  0.61944724,
         5.24879538,  2.89423173,  3.85506549

In [15]:
parameters_iris_extension = np.array([optimization_cobyla(starting_params_extension, evaluate_batch_extension, i).tolist() for i in training_sets])
parameters_iris_extension

array([[0.61888928, 4.40978076, 6.85546417, 3.18497299, 4.73730599,
        3.60506369, 1.20723205, 0.31474422, 1.51773438, 2.126691  ,
        1.88342796, 5.86841902],
       [1.04738236, 4.45372448, 7.25832118, 3.27928712, 4.95996611,
        4.06046355, 2.1499853 , 0.70106533, 2.02994171, 1.66809061,
        1.76841813, 5.34913856],
       [0.61325956, 4.26165335, 6.66984867, 3.02020132, 4.5385755 ,
        3.85680969, 1.05037527, 0.57585107, 1.43747594, 2.45182072,
        1.93655235, 6.05043482],
       [0.69646818, 3.90532662, 6.4359641 , 2.39357808, 4.32253972,
        3.25789223, 0.88702278, 0.31195469, 1.20158623, 2.22833185,
        2.07683829, 5.76621211],
       [0.64744483, 3.8399277 , 6.53629411, 2.15213204, 4.47859006,
        3.46799717, 0.89911887, 0.61716465, 1.31459443, 2.08912601,
        2.1094284 , 5.92327902],
       [1.14842662, 4.40827788, 7.45067334, 3.03142878, 5.267284  ,
        4.0797078 , 1.30925112, 0.49312994, 1.42274861, 1.90444465,
        2.12678795,

In [17]:
Accuracies_iris = np.array([evalutaion_accuracy(testing_sets[i], iris_evaluate, parameters_iris[i]) for i in range(len(testing_sets))])
Accuracies_iris

array([0.86666667, 0.85      , 0.88333333, 0.93333333, 0.88333333,
       0.86666667, 0.86666667, 0.93333333, 0.88333333, 0.88333333])

In [18]:
Accuracies_qcnn = np.array([evalutaion_accuracy(testing_sets[i], qcnn_evaluate, parameters_qcnn[i]) for i in range(len(testing_sets))])
Accuracies_qcnn

array([0.68333333, 0.91666667, 0.85      , 0.58333333, 0.56666667,
       0.75      , 0.65      , 0.75      , 0.85      , 0.73333333])

In [19]:
Accuracies_iris_extension = np.array([evalutaion_accuracy(testing_sets[i], iris_extension_evaluate, parameters_iris_extension[i]) for i in range(len(testing_sets))])
Accuracies_iris_extension

array([0.85      , 0.85      , 0.85      , 0.86666667, 0.86666667,
       0.81666667, 0.86666667, 0.81666667, 0.8       , 0.81666667])

In [20]:
print("Accuracy for iris: {}".format(Accuracies_iris.mean()))
print("Accuracy for qcnn: {}".format(Accuracies_qcnn.mean()))
print("Accuracy for iris_extension: {}".format(Accuracies_iris_extension.mean()))

Accuracy for iris: 0.885
Accuracy for qcnn: 0.7333333333333333
Accuracy for iris_extension: 0.8400000000000001
